# Generated by Django 5.2.8 on 2025-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['scout_group', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='scout_group',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='location_description',
            field=models.TextField(blank=True, help_text='Deze text wordt weergeven op de scan pagina'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='Naam van de post', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'scout_group')},
        ),
    ]
