# Generated by Django 5.2.8 on 2025-11-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_alter_group_options_group_scout_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location_description',
            new_name='description',
        ),
    ]
