# Generated by Django 5.2.8 on 2025-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_rename_location_description_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['scout_group', 'name'], 'verbose_name': 'groep', 'verbose_name_plural': 'Groepjes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order', 'name'], 'verbose_name': 'post', 'verbose_name_plural': 'posten'},
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.TextField(blank=True, help_text='Namen van groepsleden (één per regel)'),
        ),
        migrations.AddField(
            model_name='group',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contactnummer van de groep', max_length=20),
        ),
    ]
