# Generated by Django 5.2.8 on 2025-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_points', models.IntegerField(default=20, help_text='Aantal punten waarmee elke groep begint')),
                ('points_per_scan', models.IntegerField(default=20, help_text='Aantal punten per gescande post')),
                ('tag_penalty', models.IntegerField(default=1, help_text='Aantal punten aftrek per tag')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Instellingen',
                'verbose_name_plural': 'Game Instellingen',
            },
        ),
    ]
