# Generated by Django 5.2.8 on 2026-02-23 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0006_gamesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de tagger', max_length=100)),
                ('password', models.CharField(help_text='Wachtwoord om in te loggen', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'tagger',
                'verbose_name_plural': 'taggers',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagger_name',
        ),
        migrations.AddField(
            model_name='group',
            name='qr_code_identifier',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hunt.tagger'),
        ),
    ]
