# Generated by Django 5.2.8 on 2026-02-23 19:53

import uuid
from django.db import migrations


def populate_qr_codes(apps, schema_editor):
    """Populate qr_code_identifier for all groups with unique UUIDs."""
    Group = apps.get_model('hunt', 'Group')
    for group in Group.objects.all():
        group.qr_code_identifier = uuid.uuid4()
        group.save(update_fields=['qr_code_identifier'])


def reverse_populate(apps, schema_editor):
    """Reverse: nothing to do."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_extend_tagging_system'),
    ]

    operations = [
        migrations.RunPython(populate_qr_codes, reverse_populate),
    ]
