# Generated by Django 5.2.8 on 2026-02-23 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_populate_group_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='qr_code_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
