# Generated by Django 5.2.8 on 2026-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0009_make_group_qr_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='instructions/'),
        ),
    ]
